GroupManager/Models/Group.cs
namespace GroupManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Group")]
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            Posts = new HashSet<Post>();
            Quizs = new HashSet<Quiz>();
            User_Group = new HashSet<User_Group>();
        }

        public int ID { get; set; }

        [StringLength(50)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Desc { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Created_Date { get; set; }

        public int? Created_By { get; set; }

        public int? Category_ID { get; set; }

        public bool? Stt { get; set; }

        public virtual GroupCategory GroupCategory { get; set; }

        public virtual User User { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quizs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Group> User_Group { get; set; }
    }
}

GroupManager/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroupManager.Models;
using GroupManager.Functions;

namespace GroupManager.Controllers
{
    public class GroupController : Controller
    {
        // GET: Group
        private Group_Function dal = new Group_Function();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Edit(int gid, string return_url="no")
        {
            var o = dal.Get(gid);
            ViewBag.Object = o;
            var list = dal.ListCategory();
            ViewBag.GID = gid;
            ViewBag.List = list;
            ViewBag.return_url = return_url;
            if (return_url != "no")
                ViewBag.return_url = return_url;
            if (o != null)
            {
                return View();
            }
            else
                return RedirectToAction("Group","Home");
        }
        public ActionResult Create()
        {
            var list = dal.ListCategory();
            ViewBag.List = list;
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public int CreateReq(string title, string desc, int cate)
        {
            var o = new Group { 
                Title=title,
                Desc=desc,
                Category_ID=cate,
                Created_By=(int)Session["user_id"],
                Created_Date=DateTime.Now,
                Stt=true
            };
            return dal.Add(o);
        }
        [HttpPost]
        [ValidateInput(false)]
        public bool Edit(int gid, string title, string desc, int cate)
        {
            var o = dal.Get(gid);
            o.Title = title;
            o.Desc = desc;
            o.Category_ID = cate;
            return dal.Edit(o);
        }
        [HttpPost]
        [ValidateInput(false)]
        public bool AddMember(int gid, int uid)
        {
            return dal.AddUser(gid, uid);
        }

        public ActionResult DeleteMember(int gid, int uid,string return_url)
        {
            if(dal.DeleteUser(gid, uid))
                return Redirect(return_url+"?Msg=Successful!");
            else
                return Redirect(return_url + "?Msg=Error!");

        }
        public ActionResult Delete(int id, string return_url)
        {
            string msg = "";
            var stt = dal.Delete(id);
            if (stt)
            {
                msg = "Deleted successfully!";
            }
            else
                msg = "Error!";
            return Redirect(return_url + "?Msg=" + msg);
        }
    }
}

GroupManager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroupManager.Functions;
using GroupManager.Models;

namespace GroupManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string Msg="")
        {
            if (Session["login"] != null)
            {
                var dal = new User_Function();
                int user_id = (int)Session["user_id"];
                User u = dal.GetUser(user_id);
                ViewBag.CurrentUser = u;
                ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
                ViewBag.ListGroup = dal.ListGroup(user_id);
                ViewBag.ListComment = dal.ListComment(user_id);
                ViewBag.ListPost = dal.ListPost(user_id);
                ViewBag.ListReply = dal.ListReply(user_id);
                ViewBag.ListQuestion = dal.ListQuestion(user_id);

                    ViewBag.Title = "Home";
                    return View();     
            }
            else
                return RedirectToAction("Index","Login", new { area="" });
        }
        public ActionResult Post(int id, string Msg="")
        {
            ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                if (Session["login"] != null)
                {
                    var dal = new User_Function();
                    var dal_p = new Post_Function();
                    var p = dal_p.Get(id);
                    if (p != null)
                    {
                        int user_id = (int)Session["user_id"];
                            ViewBag.Title = p.Title;
                            ViewBag.Item = p;
                            ViewBag.ListCmt = dal_p.ListCmt(id);
                            return View();
                    }
                    else
                    {
                        return RedirectToAction("Group", new { Msg = "ID post không tồn tại" });
                    }
                    
                }
                else
                    return RedirectToAction("Index", "Login", new { area = "" });

            }
            else
            {
                return RedirectToAction("Group");
            }
        }
        public ActionResult Question(int id, string Msg="")
        {
            ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                if (Session["login"] != null)
                {
                    var dal = new User_Function();
                    var dal_p = new Question_Function();
                    var p = dal_p.Get(id);
                    if (p != null)
                    {
                        int user_id = (int)Session["user_id"];

                            ViewBag.Title = p.Title;
                            ViewBag.Item = p;
                            ViewBag.ListCmt = dal_p.ListCmt(id);
                            return View();
                    }
                    else
                    {
                        ViewBag.Msg = "ID post không tồn tại";
                        return RedirectToAction("Group");
                    }

                }
                else
                    return RedirectToAction("Index", "Login", new { area = "" });

            }
            else
            {
                return RedirectToAction("Group");
            }
        }
        public ActionResult DeleteQuestion(int id, string return_url = "Index")
        {
            ViewBag.Msg = "";
            var dal = new Question_Function();
            var g = dal.Get(id);
            if (g != null)
            {
                var stt = dal.Delete(id);
                if (stt)
                {
                    ViewBag.Msg = "Xóa thành công!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Msg = "Lỗi!";
                    return RedirectToAction(return_url);
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Lesson(int id, string act="no", string return_url = "Index", string Msg="")
        {
            ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
                if (!string.IsNullOrEmpty(id.ToString()))
                {
                    if (Session["login"] != null)
                    {
                        var dal = new User_Function();
                        var dal_p = new Lesson_Function();
                        var p = dal_p.Get(id);
                        if (p != null)
                        {
                                if (act == "del")
                                {
                                    var stt = dal_p.Delete(id);
                                    if (stt)
                                    {
                                        return RedirectToAction("Index", new { Msg = "Xóa thành công!" });
                                    }
                                    else
                                    {
                                        return RedirectToAction("Index", new { Msg = "Lỗi!" });
                                    }
                                }
                                else
                                if (act == "edit")
                                {
                                return View("EditLesson");
                                }
                                else
                                {
                                    ViewBag.Title = p.Title;
                                    ViewBag.Item = p;
                                    ViewBag.ListCmt = dal_p.ListCmt(id);
                                    return View();
                                }                                  
                        }
                        else
                        {
                            return RedirectToAction("Group", new { Msg = "ID không tồn tại" });
                        }

                    }
                    else
                        return RedirectToAction("Index", "Login", new { area = "" });

                }
                else
                {
                    return RedirectToAction("Group");
                }
        }
        public ActionResult Group(string s, string Msg="")
        {
            if (Session["login"] != null)
            {
                var dal = new User_Function();
                int user_id = (int)Session["user_id"];
                ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
                ViewBag.ListGroup = dal.ListGroup(user_id);
                ViewBag.ListGroupNot = dal.ListGroupNotIn(user_id);
                    if (string.IsNullOrEmpty(s))
                    {
                        ViewBag.Title = "Group";
                        return View();
                    }
                    else
                    {
                        ViewBag.Title = "Tìm kiếm";
                        ViewBag.SearchString = s;
                        ViewBag.List = new Group_Function().Search(s);
                        return View("~/Views/Home/SearchGroup.cshtml");
                    }    
            }
            else
                return RedirectToAction("Index", "Login", new { area = "" });
        }
        public ActionResult GroupDetail(int id, string s="no", string act = "no", string type = "post", string Msg="")
        {
            ViewBag.Msg = (string.IsNullOrEmpty(Msg)) ? "" : Msg;
            var user_id = (int)Session["user_id"];
            string msg = "";
            var g = new Group_Function().Get(id);
            if (g != null)
            {
                var check = new User_Function().IsInGroup(user_id, id);
                if (check || g.Created_By==user_id || new User_Function().IsAdmin(user_id))
                {
                    var dal = new User_Function();
                    ViewBag.Group = g;
                    ViewBag.CurrentID = id;
                    ViewBag.Type = type;
                    ViewBag.Title = "Chi tiết nhóm";
                    ViewBag.SearchString = s;
                    if(type=="post" && s!="no")
                    {
                        var list_search = new Post_Function().Search(s);
                        ViewBag.list_search = list_search;
                        return View();
                    }
                    else
                    if (!string.IsNullOrEmpty(act))
                    {
                        if (act == "out")
                        {
                            var stt = dal.OutGroup(user_id, id);
                            if (stt)
                            {
                                return RedirectToAction("Group", new { Msg = "Out group successfully!" });
                            }
                            else
                            {
                                Response.Write("<script>alert('Error!')</script>");
                            }
                        }
                        else
                        if (act == "del")
                        {
                            var chck = dal.IsAdminGroup(user_id,id);                         
                            if (chck)
                            {
                                var stt = dal.DeleteGroup(user_id, id);
                                if (stt)
                                {
                                    msg = "Deleted successfully!";
                                }
                                else
                                    msg="Error!";

                                return RedirectToAction("Group", new { Msg = msg });
                            }
                            else
                            {

GroupManager/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroupManager.Models;
using GroupManager.Functions;

namespace GroupManager.Controllers
{
    public class LessonController : Controller
    {
        Lesson_Function dal = new Lesson_Function();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Edit(int id, string return_url="no")
        {
            var o = dal.Get(id);
            ViewBag.Object = o;
            if (return_url != "no")
                ViewBag.return_url = return_url;
            if (o != null)
            {
                return View();
            }
            else
                return RedirectToAction("Group", "Home");
        }
        [HttpPost]
        [ValidateInput(false)]
        public bool EditLesson(int id, string title, string content)
        {
            //
            if (dal.Get(id) != null)
            {
                return dal.Edit(id,title, content);
            }
            else
                return false;
        }
        [HttpPost]
        public bool AddCmt(int pid, int uid, string content)
        {
            //
            return dal.AddComment(uid, pid, content);
        }
        public ActionResult DeleteComment(int pid, int cmt_id, string return_url = "")
        {
            //
            var stt = dal.DeleteComment(pid, cmt_id);
            if (!stt)
            {
                return Redirect(return_url);
            }
            return Redirect(return_url);
        }
        public ActionResult DeleteLesson(int id, int gid)
        {
            //
            var g = dal.Get(id);
            if (g != null)
            {
                var stt = dal.Delete(id);
                if(stt)
                {
                    return RedirectToAction("GroupDetail", "Home", new { id = gid, Msg = "Xóa thành công!" });
                }
                else
                {
                    return RedirectToAction("GroupDetail", "Home", new { id = gid, Msg = "Lỗi!" });
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id, string return_url)
        {
            string msg = "";
            var stt = dal.Delete(id);
            if (stt)
            {
                msg = "Deleted successfully!";
            }
            else
                msg = "Error!";
            return Redirect(return_url + "?Msg=" + msg);
        }
        [HttpPost]
        [ValidateInput(false)]
        public int CreateReq(int gid, string title, string desc, string content)
        {
            var o = new Lesson
            {
                Title = title,
                Group_ID = gid,
                Created_By = (int)Session["user_id"],
                Created_Date = DateTime.Now,
                Content = content,
                Stt = true
            };
            return dal.Add(o);
        }
        public ActionResult Create(int gid=-1)
        {
            ViewBag.GID = gid;
            if (gid == -1)
            {
                return View();
            }
            else
            if (new Group_Function().Get(gid) != null)
            {
                return View();
            }
            else
                return RedirectToAction("Group", "Home");
        }

    }
}

GroupManager/Views/Home/EditLesson.cshtml
@{
    ViewBag.Title = "EditLesson";
    Layout = "~/Views/Shared/_Header.cshtml";
}

<h2>EditLesson</h2>

GroupManager/Views/Home/Group.cshtml
@using GroupManager.Models
@using GroupManager.Functions
@{
    Layout = "~/Views/Shared/_Header.cshtml";
    var dal_user = new User_Function();
    var gri = (List<Group>)ViewBag.ListGroup;
    var gro = (List<Group>)ViewBag.ListGroupNot;
}


    <div class="right">
        <h3 class="heading">Danh sách</h3>
        <div class="group_list">
            <div class="search">
                <form action="" method="get">
                    <input type="text" placeholder="Tên nhóm" name="s" required>
                    <button type="submit">Tìm kiếm</button>
                </form>
            </div>
            <div class="menu">
                <ul>
                    <li><a href="@Url.Action("Create","Group")">Tạo nhóm mới</a></li>
                </ul>
                @*<select name="" id="">
                    <option value="0" selected>Danh mục</option>
                    <option value="1">Danh mục abcsder</option>
                </select>*@
            </div>
            <h4 class="left-heading">Các nhóm đã tham gia</h4>
            <div class="list">
                @if (gri != null)
                {
                    if (gri.Count > 0)
                    {
                        foreach (var item in gri)
                        {
                            <div class="items">
                                <div class="info">
                                    <span>TÊN NHÓM: <strong>@item.Title</strong></span>
                                    <span>Ngày tạo: <strong>@item.Created_Date.Value.ToString("dd/MM/yyyy")</strong></span>
                                    <span>Người tạo: <a href="#">@dal_user.GetUser((int)item.Created_By).FullName</a></span>
                                    @if ((int)Session["user_id"] == item.Created_By)
                                    {
                                        <span>Chức vụ:  <strong>ADMIN</strong></span>
                                    }
                                    else
                                    {
                                        <span>Chức vụ:  <strong>Thành viên</strong></span>
                                    }
                                </div>
                                <div class="_options">
                                    <button class="btn"><a href="@Url.Action("GroupDetail","Home")/@item.ID">Truy cập</a></button>
                                    @if (item.Created_By == (int)Session["user_id"])
                                    {
                                        <button class="btn"><a href="@Url.Action("GroupDetail","Home",new { id=item.ID, act="del" })" onclick="return confirm('Bạn có xác nhận muốn xóa?')">Xóa nhóm</a></button>
                                    }
                                    else
                                    {
                                        <button class="btn"><a href="@Url.Action("GroupDetail","Home",new { id=item.ID, act="out" })" onclick="return confirm('Bạn có xác nhận muốn rời nhóm?')">Rời nhóm</a></button>

                                    }

                                </div>
                            </div>
                        }
                    }
                }            

            </div>
            <h4 class="left-heading">Các nhóm chưa tham gia</h4>
            <div class="list">
                @if (gro != null)
                {
                    if (gro.Count > 0)
                    {
                        foreach (var item in gro)
                        {
                            <div class="items">
                                <div class="info">
                                    <span>TÊN NHÓM: <strong>@item.Title</strong></span>
                                    <span>Ngày tạo: <strong>@item.Created_Date.Value.ToString("dd/MM/yyyy")</strong></span>
                                    <span>Người tạo: <a href="#">@dal_user.GetUser((int)item.Created_By).FullName</a> </span>
                                </div>
                                <div class="_options">
                                    <div class="_options">
                                        <button class="btn"><a href="@Url.Action("TakeInGroup","Home",new { gid=item.ID })" onclick="return confirm('Bạn có xác nhận muốn tham gia nhóm này?')">Tham gia</a></button>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <p class="sgl_p">⭕ Chưa có nhóm nào</p>
                    }
                }
            </div>
        </div>
    </div>

GroupManager/Views/Home/Lesson.cshtml
@using GroupManager.Functions
@using GroupManager.Models
@{
    var post = (Lesson)ViewBag.Item;
    var dal_user = new User_Function();
    var dal_post = new Lesson_Function();
    var listcmt = (List<LessonComment>)ViewBag.ListCmt;
    int uid = (int)Session["user_id"];
    Layout = "~/Views/Shared/_Header.cshtml";
}

<script>
    $(document).ready(function () {
        var c = 0;
        var create = $('<textarea></textarea>');
        create.attr({
            'class': '_cmt',
            'id': 'txt_content_editable',
        });
        $('#cancel').hide();
        $('#submit').hide();

        $('#cancel').click(function (){
            $('#cke_txt_content_editable').hide();
            $('#submit').hide();
            $('#cancel').hide();
            $('#delete').show();
            $('#edit').show();
        });

        $('#edit').click(function () {
            $('#edit').hide();
            $('#cancel').show();
            $('#delete').hide();
            $('#submit').show();
            if (c == 0) {
                create.appendTo('#single_post');
                var default_val = `@Html.Raw(post.Content)`;
                create.val(default_val);
                CKEDITOR.replace("txt_content_editable");
                c++;
            } else {
                $('#cke_txt_content_editable').show();
            }
        });

        $("#submit").click(function (e) {
            var cont = CKEDITOR.instances['txt_content_editable'].getData();
             e.preventDefault();
                $.ajax({
                type: "POST",
                url: '@Url.Action("EditLesson","Lesson")',
                data: { 'pid': '@post.ID', 'content': cont},
                success: function (data) {
                    if (data == "True") {
                        alert("Sửa bài viết thành công!");
                        location.reload();
                    } else {
                        alert("Lỗi!")
                    }
                },
                error: function () {
                    alert("Sent request error !");
                }
            });
        })

        $("#submit_cmt").click(function (e) {
            var cont = $("#comment_content").val();
            e.preventDefault();
            console.log(cont);
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddCmt", "Lesson")',
                data: { 'pid': '@post.ID', 'content': cont, 'uid': '@uid'},
                success: function (data) {
                    if (data == "True") {
                        alert("Thành công!");
                        location.reload();
                    }
                    else
                    {
                        alert("Lỗi!")
                    }
                },
                error: function () {
                    alert("Sent request error !");
                }
            });
        })
    })
</script>

<div class="right">
    <h3 class="left-heading">@post.Title</h3>
    <div class="post_list">
        <h4 class="left-heading">
            <p>
                Đăng bởi <span>@dal_user.GetUser((int)post.Created_By).FullName</span> vào lúc @post.Created_Date.Value.ToString("dd/MM/yyyy")
            </p>
        </h4>
        <div class="list" id="single_post">
            <div class="items sgl_post">
                <span class="_content" id="txt_content">
                    @Html.Raw(Server.HtmlDecode(post.Content))
                    @if ((int)Session["user_id"] == (int)post.Created_By)
                    {
                        <p class="owner_options">
                            <span class="sbm" id="submit"><i class="fas fa-clipboard-check"></i><a href="#">Xác nhận</a> </span>
                            <span id="edit"><i class="fas fa-edit"></i><a href="#">Sửa</a> </span>
                            <span id="cancel"><i class="fas fa-edit"></i><a href="#">Hủy</a></span>
                            <span id="delete"><i class="fas fa-trash-alt"></i><a href="@Url.Action("DeleteLesson", "Lesson", new { id = post.ID, gid=post.Group_ID })" onclick="return confirm('Bạn có xác nhận muốn xóa?')">Xóa</a></span>
                        </p>
                    }
            </div>
        </div>
        <div class="list cmt_section">
            <form action="" class="_cmt">
                <textarea name="comment" id="comment_content" cols="30" rows="5" required></textarea>
                <button type="submit" class="btn" id="submit_cmt">Bình luận</button>
            </form>
            <div class="list_comment">
                @if (listcmt != null)
                {
                    if (listcmt.Count > 0)
                    {
                        foreach (var item in listcmt)
                        {
                            <div class="sgl_cmt">
                                <p><strong>@dal_user.GetUser((int)item.Created_By).FullName</strong> vào lúc <strong>@item.Created_Date.Value.ToString("dd/MM/yyyy")</strong></p>
                                <p>@item.Content</p>
                                @if ((int)Session["user_id"] == (int)item.Created_By)
                                {
                                    @*<span><a href="#"> Sửa </a></span>*@
                                    <span><a href="@Url.Action("DeleteComment","Lesson", new { pid=item.Lesson_ID, cmt_id = item.ID, return_url=HttpContext.Current.Request.Url.AbsoluteUri })" onclick="return confirm('Bạn có xác nhận muốn xóa?')"> Xóa </a></span>
                                }
                            </div>
                        }
                    }
                    else
                    {
                        <p class="sgl_p">⭕ Chưa có bình luận nào</p>
                    }
                }


            </div>
        </div>
    </div>
</div>

GroupManager/Views/Home/SearchGroup.cshtml
@using GroupManager.Models
@using GroupManager.Functions
@{
    Layout = "~/Views/Shared/_Header.cshtml";
    var List = (List<Group>)ViewBag.List;
    var dal = new User_Function();
}


<div class="right">
    <h3 class="heading">Tìm kiếm nhóm</h3>
    <div class="group_list">
        <div class="search">
            <form action="" method="get">
                <input type="text" placeholder="Tên nhóm" name="s" required>
                <button type="submit">Tìm kiếm</button>
            </form>
        </div>
        <h4 class="left-heading">Tìm thấy @List.Count kết quả cho từ khóa "@ViewBag.SearchString"</h4>
        <div class="list">
            @if (List.Count > 0)
            {
                foreach (var item in List)
                {
                    var name = dal.GetUser((int)item.Created_By).FullName;
                    <div class="items">
                        <div class="info">
                            <span>TÊN NHÓM: <strong>@item.Title</strong></span>
                            <span>Ngày tạo: <strong>@item.Created_Date.Value.ToString("dd/MM/yyyy")</strong></span>
                            <span>Người tạo: <a href="#">@name</a> </span>
                        </div>
                        <div class="_options">
                            @if ( dal.IsInGroup((int)Session["user_id"],item.ID) ){
                                <button class="btn"><a href="#">Truy cập</a></button>
                            }else
                            {
                                <button class="btn"><a href="#">Tham gia</a></button>
                            }
                            
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>